create_message :
    path: /messages
    controller: App\Controller\MessageController::create
    methods: POST

get_messages :
    path: /messages
    controller: App\Controller\MessageController::getAll
    methods: GET
